### ISSUE TITLE
Is it possible to pass custom config to FNC when flashing?

### ISSUE THREAD

**Issue by lukevenediger** [cesanta/fnc#2]
Hi,

I use FNC to flash my ESP8266 but I have to run make each time I want to customise the config file before flashing. Is there a way I can pass in conf.json to FNC so that I can customise my configuration each time I flash? This will let me, say, generate device IDs dynamically.

Thanks,
Luke

**Comment by rojer** [comment]
not at the moment. it's something we're considering, but no concrete plans or ETA yet though.

**Comment by mmikulicic** [comment]
You can build your own firmware and put your custom conf in `smartjs/src/fs/conf_vendor.json`

**Comment by rojer** [comment]
he's building his own firmware already, his question is whether it's possible to make changes without rebuilding it all the time. currently the answer is no.

**Comment by mmikulicic** [comment]
yeah, sorry I misread.

@lukevenediger if you don't mind some scripting, you can take a look at `unspiffs` (https://github.com/cesanta/smart.js/tree/master/common/spiffs/tools) and `fw_meta.py get_build_info` and `fw_meta.py create_manifest` (https://github.com/cesanta/smart.js/blob/master/common/tools/fw_meta.py).

With them you can modify the contents of a spiffs filesystem bundled in the firmware zip file.
We use it in our continuous integration system to patch a pre-built firmware with wifi config for example.

It's out of the scope of FnC, hence closing this issue.
Please share you experience with `unspiffs` on the smartjs issue tracker or on our forums.

**Comment by lukevenediger** [comment]
Ok thanks @mmikulicic! That seems like a good way to go and I'll give it a try.
